# Generated by Django 5.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_cancellation_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason provided by tenant for cancellation', null=True),
        ),
    ]
