# Generated by Django 5.0.1

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_reset_service_catalog_to_new_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecatalog',
            name='estimated_price_max',
        ),
        migrations.RemoveField(
            model_name='servicecatalog',
            name='estimated_price_min',
        ),
        migrations.AlterField(
            model_name='servicecatalog',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Service price (must be under EUR 100)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
