# Generated by Django 5.0.1 on 2026-09-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_remove_servicecatalog_estimated_price_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceimage',
            name='image',
            field=models.FileField(upload_to='maintenance_images/'),
        ),
    ]
