# Generated by Django 5.0.1 on 2026-09-08 08:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_alter_maintenanceimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='landlord_quote_response_note',
            field=models.TextField(blank=True, help_text="Landlord's comment when approving/rejecting/requesting revision"),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='quote_document',
            field=models.FileField(blank=True, help_text='Optional PDF/file with the cost proposal', null=True, upload_to='quote_documents/'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='quote_note',
            field=models.TextField(blank=True, help_text="Admin's message to the landlord about the quote"),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='quote_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='quote_status',
            field=models.CharField(choices=[('none', 'No Quote Yet'), ('pending', 'Pending Landlord Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_requested', 'Revision Requested')], default='none', max_length=25),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='quoted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='quoted_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
