# Generated by Django 5.0.1 on 2026-09-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_maintenancerequest_landlord_quote_response_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='category',
            field=models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('hvac', 'HVAC'), ('appliance', 'Appliance'), ('structural', 'Structural'), ('cleaning', 'Cleaning'), ('painting', 'Painting'), ('carpentry', 'Carpentry'), ('locksmith', 'Locksmith'), ('gardening', 'Gardening'), ('pest_control', 'Pest Control'), ('general_maintenance', 'General Maintenance'), ('other', 'Other')], max_length=50),
        ),
    ]
