# Generated by Django 5.0.1 on 2026-01-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_approval_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
