# Generated by Django 5.0.1 on 2026-01-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_property_monthly_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rental_terms',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
