# Generated by Django 5.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_property_rental_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('room', 'Room'), ('condo', 'Condo'), ('villa', 'Villa'), ('studio', 'Studio'), ('townhouse', 'Townhouse'), ('other', 'Other')], max_length=50),
        ),
    ]
